Presentation/mvcPet.UI.Web/Controllers/TipoMovimientoController.cs
using mvcPet.Entities;
using mvcPet.Services;
using mvcPet.Services.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvcPet.UI.Web.Controllers
{
    public class TipoMovimientoController : Controller
    {
        // GET: TipoMovimiento
        public ActionResult Index()
        {
            ITipoMovimientoService tipoMovimientoService = new TipoMovimientoService();
            var lista = tipoMovimientoService.ListarTodos();

            return View(lista);
        }

        // GET: TipoMovimiento/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: TipoMovimiento/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TipoMovimiento/Create
        [HttpPost]
        public ActionResult Create(TipoMovimiento model)
        {
            try
            {
                // TODO: Add insert logic here *****************aca toque GABY-----
                ITipoMovimientoService tipoMovimientoService = new TipoMovimientoService();
                tipoMovimientoService.Agregar(model);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: TipoMovimiento/Edit/5 *****************aca toque GABY-----
        public ActionResult Edit(int id)
        {
            ITipoMovimientoService tipoMovimiento = new TipoMovimientoService();
            TipoMovimiento t = tipoMovimiento.BuscarPorId(id);
            return View(t);
        }

        // POST: TipoMovimiento/Edit/5 ***************aca toque GABY
        [HttpPost]
        public ActionResult Edit(TipoMovimiento model)
        {
            try
            {
                // TODO: Add update logic here  
                ITipoMovimientoService tipoMovimientoService = new TipoMovimientoService();
                tipoMovimientoService.Editar(model);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: TipoMovimiento/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: TipoMovimiento/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Presentation/mvcPet.UI.Web/Controllers/TipoServicioController.cs
using mvcPet.Entities;
using mvcPet.Services;
using mvcPet.Services.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvcPet.UI.Web.Controllers
{
    public class TipoServicioController : Controller
    {
        // GET: TipoServicio
        public ActionResult Index()
        {
            ITipoServicioService tipoServicioService = new TipoServicioService();
            var lista = tipoServicioService.ListarTodos();

            return View(lista);
        }

        // GET: TipoServicio/ListaPrecios/5
        public ActionResult ListaPrecios(int id)
        {
            ITipoServicioService tipoServicioService = new TipoServicioService();
            var tipoServicio = tipoServicioService.BuscarPorId(id);

            IPrecioService precioService = new PrecioService();
            var precios = precioService.BuscarPorTipoServicio(id);

            tipoServicio.Precios = new List<Precio>(precios);

            return View(tipoServicio);
        }

        // GET: TipoServicio/NuevoPrecio
        public ActionResult NuevoPrecio(int id)
        {
            try
            {
                ITipoServicioService tipoServicioService = new TipoServicioService();
                var tipoServicio = tipoServicioService.BuscarPorId(id);

                IPrecioService precioService = new PrecioService();
                var precio = new Precio
                {
                    TipoServicioId = id,
                    TipoServicio = tipoServicio
                };

                return View(precio);
            }
            catch (Exception)
            {
                return View();
                throw;
            }
        }

        // POST: TipoServicio/NuevoPrecio
        [HttpPost]
        public ActionResult NuevoPrecio(Precio precio)
        {
            try
            {
                IPrecioService precioService = new PrecioService();
                precioService.Agregar(precio);
                return RedirectToAction("ListaPrecios", new { id = precio.TipoServicioId } );
            }
            catch
            {
                return View();
            }
        }

        // GET: TipoServicio/EditarPrecio/5
        public ActionResult EditarPrecio(int? id)
        {

            if (id == null)
            {
                return HttpNotFound();
            }

            IPrecioService precioService = new PrecioService();
            Precio precio = precioService.BuscarPorId(id.Value);

            if(precio == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(precio);
            }

        }

        // POST: TipoServicio/EditarPrecio/5
        [HttpPost]
        public ActionResult EditarPrecio(Precio precio)
        {
            try
            {
                IPrecioService precioService = new PrecioService();
                precioService.Editar(precio);
                return RedirectToAction("ListaPrecios", new { id = precio.TipoServicioId });
            }
            catch
            {
                return View();
            }
        }

        // GET: TipoServicio/Details/5
        public ActionResult Details(int id)
        {
            ITipoServicioService tipoServicioService = new TipoServicioService();
            var tipoServicio = tipoServicioService.BuscarPorId(id);

            if(tipoServicio == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(tipoServicio);
            }

        }

        // GET: TipoServicio/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TipoServicio/Create
        [HttpPost]
        public ActionResult Create(TipoServicio model)
        {
            try
            {
                ITipoServicioService tipoServicioService = new TipoServicioService();
                tipoServicioService.Agregar(model);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: TipoServicio/Edit/5
        public ActionResult Edit(int id)
        {
            ITipoServicioService tipoServicioService = new TipoServicioService();
            TipoServicio tipoServicio = tipoServicioService.BuscarPorId(id);
            return View(tipoServicio);
        }

        // POST: TipoServicio/Edit/5
        [HttpPost]
        public ActionResult Edit(TipoServicio tipoServicio)
        {
            try
            {
                ITipoServicioService tipoServicioService = new TipoServicioService();
                tipoServicioService.Editar(tipoServicio);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: TipoServicio/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: TipoServicio/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Presentation/mvcPet.UI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Veterinaria</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Veterinaria", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sobre Nosotros", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                        @* dropdown *@
                        @Html.Partial("_MenuPartial")
                </ul>
                        @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Arquitectura web</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Presentation/mvcPet.UI.Web/Views/Shared/_MenuPartial.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    @*<ul class="nav navbar-nav">
        <li></li>
    </ul>*@

    <li class="dropdown">
        <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">A.B.M.<span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
            <li>@Html.ActionLink("Especies", "Index", "Especies")</li>
            <li>@Html.ActionLink("Sala", "Index", "Sala")</li>
            <li>@Html.ActionLink("Tipo de Movimiento", "Index", "TipoMovimiento")</li>
            <li>@Html.ActionLink("Tipos de Servicios", "Index", "TipoServicio")</li>
        </ul>
    </li>
}